meta:
  name: 6adm.in
  url: ""
  description: "Exploring exciting things."
  logo: /logo.png
  footerInfo: La connaissance s'acquiert par l'expérience, tout le reste n'est que de l'information -- Albert Einstein 
post:
  showFeatureImage: true
  featureText: featured
appearance:
  mainColor: "#C668B9"
  linkHoverColor: "#C668B9"
component:
  authorBox: true
  codeLineNumbers: true
